Better server
jstriebel/ai-car pull request #3
Opened 2017-08-12 10:26 UTC by lucaschimweg

Added a better server :)

2017-08-12 16:34 UTC, jstriebel requested changes
Generally LGTM, just some minor issues that I commented in the code.

2017-08-12 16:34 UTC, jstriebel commented on collect_data.py
> +            "/": FileHandler("index.html"),
I would prefer to have `FileHandler(…)` above with the other two handlers to keep it consistent.

2017-08-12 16:34 UTC, jstriebel commented on handlers/video_handler.py
>  from writers.writer import Writer
Please order the imports like this:
1. Alphabetically all external libraries
2. Newline
3. Alphabetically all internal imports

2017-08-12 16:34 UTC, jstriebel commented on handlers/video_handler.py
> +        self.frame = data
Please add the final newline

2017-08-12 16:44 UTC, lucaschimweg commented
@jstriebel I fixed the problems, could you have a look at the code again?

2017-08-13 15:54 UTC, jstriebel commented
This is fine from my side, @normanrz, could you have a look, too?

2017-08-13 15:54 UTC, jstriebel approved these changes

2017-08-13 15:59 UTC, normanrz approved these changes
lgtm

2017-08-13 15:59 UTC, merged